---
- name: resolving vars...
  include_vars:
    file: install-vars.yml
- name: download....
  become: yes
  become_user: root
  get_url:
    url: '{{ prometheus_installer_tgz_url }}'
    dest: /tmp/{{ prometheus_installer_tgz }}
    checksum: '{{ prometheus_installer_checksum }}'
    mode: 0644

- name: unarchive...
  become: yes
  become_user: root
  unarchive:
    remote_src: yes
    src: /tmp/{{ prometheus_installer_tgz }}
    dest: '{{ prometheus_installer_parent_dir }}'
    creates: '{{ prometheus_installer_dir }}'

- name: linking...
  become: yes
  become_user: root
  file:
    src: '{{ prometheus_installer_dir }}'
    dest: '{{ prometheus_installer_link_dir }}'
    state: link

- name: add to default path...
  become: yes
  become_user: root
  template:
    src: shell.j2
    dest: /etc/profile.d/{{ prometheus_installer_app.name }}.sh
    mode: 0644
